[build-system]
requires = [
    "hatchling",
    "hatch-vcs"
]
build-backend = "hatchling.build"


[project]
name = "lourido"
dynamic = [
    "version"
]
license = "MIT"
requires-python = ">=3.11"
dependencies = [
    "nastro"
]

[project.optional-dependencies]
test = [
    "pytest"
]

[tool.hatch]
version.source = "vcs"
build.hooks.vcs.version-file = "src/lourido/_version.py"
